name: Build and test coexist on OS and Python version matrix

env:
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: "pytest {project}/tests"
#   CIBW_BUILD: cp37-* cp38-* cp39-*

# Disable building PyPy wheels on all platforms
# env:
#   CIBW_SKIP: pp*


# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]
# Manually trigger workflow
# on: workflow_dispatch

jobs:
  build_wheels:
    name: Build coexist wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install package dependencies
        uses: py-actions/py-dependency-install@v2

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
